version: '3.9'

services:
  frontend:
    image: musiclib
    build:
      context: ./music-library-ui
      dockerfile: Dockerfile
    ports:
      - "80:4200"
    depends_on:
      - backend

  backend:
    image: musiclib-svc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mldb
    volumes:
      - './dockervolume/mongodb:/data/db'

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      # ME_CONFIG_MONGODB_AUTH_DATABASE: mldb
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      